## Example use of interpolate_table method

In [1]:
import numpy as np
from interpolate_repeated_table import interpolate_table

Load file of table with repeated values.

In [2]:
out = np.loadtxt('file.csv')

Use cases:

In [3]:
interpolate_table(out, coordinates=[0, 10, 0.5])

array([0.582412 , 0.2818265])

In [4]:
interpolate_table(out, coordinates=[0, 10, 0.5], DV_columns=[4, 3])

array([0.2818265, 0.582412 ])

In [5]:
interpolate_table(out, coordinates=[0, 15, 0.5])

array([0.3372805, 0.363981 ])

In [6]:
interpolate_table(out, coordinates=[0, 15])

array([0.       , 0.3755535, 0.457887 ])

In [7]:
interpolate_table(out, coordinates=[0])

array([10.      ,  0.      ,  0.664915,  0.54909 ])